### ISSUE TITLE
程序报错，弹幕文件未正常保存

### ISSUE THREAD

**Issue by InterestingFred** [acgnhiki/blrec#127]
发生错误使得无法保存.xml文件，文件显示不存在，不知道为啥，报错如下求解答
录制文件正常且硬盘空间是够的

Traceback (most recent call last):
  File "/app/src/blrec/core/raw_danmaku_dumper.py", line 98, in _do_dump
    async for attempt in AsyncRetrying(
  File "/usr/local/lib/python3.10/site-packages/tenacity/_asyncio.py", line 69, in __anext__
    do = self.iter(retry_state=self._retry_state)
  File "/usr/local/lib/python3.10/site-packages/tenacity/__init__.py", line 349, in iter
    return fut.result()
  File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
  File "/app/src/blrec/core/raw_danmaku_dumper.py", line 104, in _do_dump
    await self._dumping_loop(f)
  File "/app/src/blrec/core/raw_danmaku_dumper.py", line 119, in _dumping_loop
    danmu = await self._receiver.get_raw_danmaku()
  File "/app/src/blrec/core/raw_danmaku_receiver.py", line 33, in get_raw_danmaku
    return await self._queue.get()
  File "/usr/local/lib/python3.10/asyncio/queues.py", line 159, in get
    await getter
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/src/blrec/event/event_emitter.py", line 41, in _emit
    await coro(*args, **kwds)
  File "/app/src/blrec/core/raw_danmaku_dumper.py", line 71, in on_video_file_completed
    await self._stop_dumping()
  File "/app/src/blrec/core/raw_danmaku_dumper.py", line 78, in _stop_dumping
    await self._cancel_dump_task()
  File "/app/src/blrec/core/raw_danmaku_dumper.py", line 88, in _cancel_dump_task
    await self._dump_task
  File "/app/src/blrec/event/event_emitter.py", line 41, in _emit
    await coro(*args, **kwds)
  File "/app/src/blrec/core/raw_danmaku_dumper.py", line 66, in on_video_file_created
    await self._stop_dumping()
  File "/app/src/blrec/core/raw_danmaku_dumper.py", line 78, in _stop_dumping
    await self._cancel_dump_task()
  File "/app/src/blrec/core/raw_danmaku_dumper.py", line 88, in _cancel_dump_task
    await self._dump_task
  File "/app/src/blrec/core/raw_danmaku_dumper.py", line 78, in _stop_dumping
    await self._cancel_dump_task()
  File "/app/src/blrec/core/raw_danmaku_dumper.py", line 88, in _cancel_dump_task
    await self._dump_task
  File "/app/src/blrec/event/event_emitter.py", line 41, in _emit
    await coro(*args, **kwds)
  File "/app/src/blrec/core/raw_danmaku_dumper.py", line 71, in on_video_file_completed
    await self._stop_dumping()
  File "/app/src/blrec/core/raw_danmaku_dumper.py", line 78, in _stop_dumping
    await self._cancel_dump_task()
  File "/app/src/blrec/core/raw_danmaku_dumper.py", line 88, in _cancel_dump_task
    await self._dump_task
  File "/app/src/blrec/event/event_emitter.py", line 41, in _emit
    await coro(*args, **kwds)
  File "/app/src/blrec/core/raw_danmaku_dumper.py", line 66, in on_video_file_created
    await self._stop_dumping()
  File "/app/src/blrec/core/raw_danmaku_dumper.py", line 78, in _stop_dumping
    await self._cancel_dump_task()
  File "/app/src/blrec/core/raw_danmaku_dumper.py", line 88, in _cancel_dump_task
    await self._dump_task
  File "/app/src/blrec/core/raw_danmaku_dumper.py", line 78, in _stop_dumping
    await self._cancel_dump_task()
  File "/app/src/blrec/core/raw_danmaku_dumper.py", line 88, in _cancel_dump_task
    await self._dump_task
  File "/app/src/blrec/event/event_emitter.py", line 41, in _emit
    await coro(*args, **kwds)
  File "/app/src/blrec/core/raw_danmaku_dumper.py", line 71, in on_video_file_completed
    await self._stop_dumping()
  File "/app/src/blrec/core/raw_danmaku_dumper.py", line 78, in _stop_dumping
    await self._cancel_dump_task()
  File "/app/src/blrec/core/raw_danmaku_dumper.py", line 88, in _cancel_dump_task
    await self._dump_task
  File "/app/src/blrec/event/event_emitter.py", line 41, in _emit
    await coro(*args, **kwds)
  File "/app/src/blrec/core/raw_danmaku_dumper.py", line 66, in on_video_file_created
    await self._stop_dumping()
  File "/app/src/blrec/core/raw_danmaku_dumper.py", line 78, in _stop_dumping
    await self._cancel_dump_task()
  File "/app/src/blrec/core/raw_danmaku_dumper.py", line 88, in _cancel_dump_task
    await self._dump_task
  File "/app/src/blrec/core/raw_danmaku_dumper.py", line 78, in _stop_dumping
    await self._cancel_dump_task()
  File "/app/src/blrec/core/raw_danmaku_dumper.py", line 88, in _cancel_dump_task
    await self._dump_task
  File "/app/src/blrec/logging/room_id.py", line 42, in wrapper
    return await func(obj, *arg, **kwargs)
  File "/app/src/blrec/core/raw_danmaku_dumper.py", line 94, in _do_dump
    async with aiofiles.open(self._path, 'wt', encoding='utf8') as f:
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
OSError: [Errno 28] No space left on device

**Comment by acgnhiki** [comment]
```
OSError: [Errno 28] No space left on device
```

硬盘满了

**Comment by InterestingFred** [comment]
但是录制文件能正常保存 并且在录制开始时就有这一报错信息
之前服务器确实有一次满了 但是清理后仍然产生这一提示并且弹幕无法录制
附近期日志
[log.txt](https://github.com/acgnhiki/blrec/files/9945229/log.txt)

**Comment by acgnhiki** [comment]
> 但是录制文件能正常保存 并且在录制开始时就有这一报错信息 之前服务器确实有一次满了 但是清理后仍然产生这一提示并且弹幕无法录制 附近期日志 [log.txt](https://github.com/acgnhiki/blrec/files/9945229/log.txt)

硬盘满了程序崩了，清理后重新运行了？

**Comment by InterestingFred** [comment]
爆满后对文件进行了清理 但并未重启blrec，日志文件2022年8月27日产生的，运行版本是191，docker，截取了部分 整个文件太大了，我重启试试
