### ISSUE TITLE
1.3.0  开播录制依旧报错

### ISSUE THREAD

**Issue by chang147** [acgnhiki/blrec#13]
[2022-01-23 19:08:52,812] [DEBUG] [retry] [XXXXXX] Retry main_loop after 1.0 seconds
[2022-01-23 19:08:53,972] [DEBUG] [stream_recorder] [XXXXXX] Got live stream url: 'https://d1--cn-gotcha08.bilivideo.com/live-bvc/238358/live_9253035_2208609.flv?expires=1642939793&len=0&oi=620441922&pt=web&qn=10000&trid=1000f9d1d4b58a17438981e644a0ea5bcad0&sigparams=cdn,expires,len,oi,pt,qn,trid&cdn=cn-gotcha08&sign=fa67181fa59c0fc6a7d05585fa647d2d&sk=03d046f969c9ebd72581fe8b44bbb402c58f0b243430a8107ea8d106378f6798&p2p_type=1&src=128&sl=1&free_type=0&flowtype=0&machinezone=jd&pp=rtmp&slot=4&source=onetier&order=1&site=e0fccbca3cec20db29c0b2ddff4f0504'
[2022-01-23 19:08:53,973] [DEBUG] [stream_recorder] [XXXXXX] Getting the live stream...
[2022-01-23 19:08:54,146] [DEBUG] [stream_recorder] [XXXXXX] Response received
[2022-01-23 19:08:54,147] [DEBUG] [stream_processor] [XXXXXX] Processing the 3th stream...
[2022-01-23 19:08:54,148] [DEBUG] [stream_processor] [XXXXXX] frame rate: 60.0, video frame interval: 17
[2022-01-23 19:08:54,174] [DEBUG] [stream_processor] [XXXXXX] Reading tags for tag deduplication...
[2022-01-23 19:09:08,566] [DEBUG] [stream_processor] [XXXXXX] Read 2140 tags, total size: 23351652
[2022-01-23 19:09:08,566] [DEBUG] [stream_processor] [XXXXXX] Finding duplicated tags...
[2022-01-23 19:09:08,567] [ERROR] [stream_recorder] [XXXXXX] list index out of range
Traceback (most recent call last):
  File "E:\blrec-1.3.0-win64\python-3.10.1-embed-amd64\Lib\site-packages\blrec\core\stream_recorder.py", line 278, in _main_loop
    self._streaming_loop()
  File "E:\blrec-1.3.0-win64\python-3.10.1-embed-amd64\Lib\site-packages\blrec\core\stream_recorder.py", line 307, in _streaming_loop
    self._streaming(url)
  File "E:\blrec-1.3.0-win64\python-3.10.1-embed-amd64\Lib\site-packages\blrec\core\stream_recorder.py", line 355, in _streaming
    self._stream_processor.process_stream(
  File "E:\blrec-1.3.0-win64\python-3.10.1-embed-amd64\Lib\site-packages\blrec\flv\stream_processor.py", line 142, in process_stream
    self._process_stream(stream)
  File "E:\blrec-1.3.0-win64\python-3.10.1-embed-amd64\Lib\site-packages\blrec\flv\stream_processor.py", line 217, in _process_stream
    self._process_subsequent_stream(first_data_tag)
  File "E:\blrec-1.3.0-win64\python-3.10.1-embed-amd64\Lib\site-packages\blrec\flv\stream_processor.py", line 247, in _process_subsequent_stream
    if (index := self._find_last_duplicated_tag(tags)) >= 0:
  File "E:\blrec-1.3.0-win64\python-3.10.1-embed-amd64\Lib\site-packages\blrec\flv\stream_processor.py", line 413, in _find_last_duplicated_tag
    last_out_tag = self._last_tags[0]
IndexError: list index out of range
[2022-01-23 19:09:08,575] [DEBUG] [retry] [XXXXXX] Retry main_loop after 1.0 seconds

**Comment by threewatermeter** [comment]
[2022-01-23 22:52:25,475] [ERROR] [stream_recorder] [146088] list index out of range
Traceback (most recent call last):
  File "C:\Python39\lib\site-packages\blrec\core\stream_recorder.py", line 278, in `_main_loop`
    self._streaming_loop()
  File "C:\Python39\lib\site-packages\blrec\core\stream_recorder.py", line 307, in _streaming_loop
    self._streaming(url)
  File "C:\Python39\lib\site-packages\blrec\core\stream_recorder.py", line 355, in _streaming
    self._stream_processor.process_stream(
  File "C:\Python39\lib\site-packages\blrec\flv\stream_processor.py", line 142, in process_stream
    self._process_stream(stream)
  File "C:\Python39\lib\site-packages\blrec\flv\stream_processor.py", line 217, in _process_stream
    self._process_subsequent_stream(first_data_tag)
  File "C:\Python39\lib\site-packages\blrec\flv\stream_processor.py", line 247, in _process_subsequent_stream
    if (index := self._find_last_duplicated_tag(tags)) >= 0:
  File "C:\Python39\lib\site-packages\blrec\flv\stream_processor.py", line 413, in _find_last_duplicated_tag
    last_out_tag = self._last_tags[0]
IndexError: list index out of range
[2022-01-23 22:52:25,477] [DEBUG] [retry] [146088] Retry main_loop after 1.0 seconds
[2022-01-23 22:52:26,795] [DEBUG] [stream_recorder] [146088] Got live stream url: 'https://d1--cn-gotcha08.bilivideo.com/live-bvc/124880/live_642922_6488739.flv?expires=1642953207&len=0&oi=992617816&pt=web&qn=10000&trid=10009c682a132c444a5893a97d800ccddf83&sigparams=cdn,expires,len,oi,pt,qn,trid&cdn=cn-gotcha08&sign=ecde39284083562bfd568cbc4755a416&sk=49f8300a38493ac4b81f5f7e958b0ff2&p2p_type=1&src=129&sl=2&free_type=0&flowtype=1&machinezone=jd&pp=srt&slot=7&source=onetier&order=1&site=438afc81af5b27fff7d7c2b72af0f821'
[2022-01-23 22:52:26,795] [DEBUG] [stream_recorder] [146088] Getting the live stream...
[2022-01-23 22:52:26,999] [DEBUG] [stream_recorder] [146088] Response received
[2022-01-23 22:52:26,999] [DEBUG] [stream_processor] [146088] Processing the 719th stream...
[2022-01-23 22:52:27,001] [DEBUG] [stream_processor] [146088] frame rate: 30.0, video frame interval: 34
[2022-01-23 22:52:27,039] [DEBUG] [stream_processor] [146088] Reading tags for tag deduplication...
[2022-01-23 22:52:40,475] [DEBUG] [stream_processor] [146088] Read 1463 tags, total size: 15450654
[2022-01-23 22:52:40,475] [DEBUG] [stream_processor] [146088] Finding duplicated tags...

**Comment by acgnhiki** [comment]
v1.3.1  2f65aa54cae08a3ac7c2d80c3314c82814dbc69d 
复现不了没测试，有问题再反馈下。

**Comment by chang147** [comment]
V1.3.1 依旧报错

直接在Release 下载blrec-1.3.1-win64.zip 后在电脑解压缩
现象：
1.直播间已经开播，运行.bat可以录制，但是录播视频地址会自动改成默认地址（B站录播）与settings.toml文件中设定不符
2.先运行.bat 脚本 >1H，主播开始直播则报错文件如附件，报错时间[2022-01-25 18:56:33,846]，但是文件可以正常录制，同样录播视频地址会自动改成默认地址
[blrec_2022-01-25-112336.log](https://github.com/acgnhiki/blrec/files/7938374/blrec_2022-01-25-112336.log)

**Comment by acgnhiki** [comment]
> > v1.3.1 [2f65aa5](https://github.com/acgnhiki/blrec/commit/2f65aa54cae08a3ac7c2d80c3314c82814dbc69d) 复现不了没测试，有问题再反馈下。
> 
> 1.3.1报错: [2022-01-25 23:18:13,595] [ERROR] [stream_recorder] [146088] Invalid Tag Traceback (most recent call last): File "C:\Users\ysz19.local\pipx\venvs\blrec\lib\site-packages\blrec\core\stream_recorder.py", line 278, in _main_loop self._streaming_loop() File "C:\Users\ysz19.local\pipx\venvs\blrec\lib\site-packages\blrec\core\stream_recorder.py", line 307, in _streaming_loop self._streaming(url) File "C:\Users\ysz19.local\pipx\venvs\blrec\lib\site-packages\blrec\core\stream_recorder.py", line 355, in _streaming self._stream_processor.process_stream( File "C:\Users\ysz19.local\pipx\venvs\blrec\lib\site-packages\blrec\flv\stream_processor.py", line 141, in process_stream self._process_stream(stream) File "C:\Users\ysz19.local\pipx\venvs\blrec\lib\site-packages\blrec\flv\stream_processor.py", line 213, in _process_stream first_data_tag = self._read_first_data_tag() File "C:\Users\ysz19.local\pipx\venvs\blrec\lib\site-packages\blrec\flv\stream_processor.py", line 434, in _read_first_data_tag for tag in self._read_tags_from_in_stream(): File "C:\Users\ysz19.local\pipx\venvs\blrec\lib\site-packages\blrec\flv\stream_processor.py", line 372, in _read_tags_from_in_stream tag = self._in_reader.read_tag() File "C:\Users\ysz19.local\pipx\venvs\blrec\lib\site-packages\blrec\flv\stream_processor.py", line 712, in read_tag tag = super().read_tag(no_body=no_body) File "C:\Users\ysz19.local\pipx\venvs\blrec\lib\site-packages\blrec\flv\io.py", line 30, in read_tag tag = self._parser.parse_tag(no_body=no_body) File "C:\Users\ysz19.local\pipx\venvs\blrec\lib\site-packages\blrec\flv\format.py", line 52, in parse_tag tag_header = self.parse_flv_tag_header() File "C:\Users\ysz19.local\pipx\venvs\blrec\lib\site-packages\blrec\flv\format.py", line 84, in parse_flv_tag_header assert data_size > 0, 'Invalid Tag' AssertionError: Invalid Tag [2022-01-25 23:18:15,090] [ERROR] [stream_recorder] [146088] Invalid Tag Traceback (most recent call last): File "C:\Users\ysz19.local\pipx\venvs\blrec\lib\site-packages\blrec\core\stream_recorder.py", line 278, in _main_loop self._streaming_loop() File "C:\Users\ysz19.local\pipx\venvs\blrec\lib\site-packages\blrec\core\stream_recorder.py", line 307, in _streaming_loop self._streaming(url) File "C:\Users\ysz19.local\pipx\venvs\blrec\lib\site-packages\blrec\core\stream_recorder.py", line 355, in _streaming self._stream_processor.process_stream( File "C:\Users\ysz19.local\pipx\venvs\blrec\lib\site-packages\blrec\flv\stream_processor.py", line 141, in process_stream self._process_stream(stream) File "C:\Users\ysz19.local\pipx\venvs\blrec\lib\site-packages\blrec\flv\stream_processor.py", line 213, in _process_stream first_data_tag = self._read_first_data_tag() File "C:\Users\ysz19.local\pipx\venvs\blrec\lib\site-packages\blrec\flv\stream_processor.py", line 434, in _read_first_data_tag for tag in self._read_tags_from_in_stream(): File "C:\Users\ysz19.local\pipx\venvs\blrec\lib\site-packages\blrec\flv\stream_processor.py", line 372, in _read_tags_from_in_stream tag = self._in_reader.read_tag() File "C:\Users\ysz19.local\pipx\venvs\blrec\lib\site-packages\blrec\flv\stream_processor.py", line 712, in read_tag tag = super().read_tag(no_body=no_body) File "C:\Users\ysz19.local\pipx\venvs\blrec\lib\site-packages\blrec\flv\io.py", line 30, in read_tag tag = self._parser.parse_tag(no_body=no_body) File "C:\Users\ysz19.local\pipx\venvs\blrec\lib\site-packages\blrec\flv\format.py", line 52, in parse_tag tag_header = self.parse_flv_tag_header() File "C:\Users\ysz19.local\pipx\venvs\blrec\lib\site-packages\blrec\flv\format.py", line 84, in parse_flv_tag_header assert data_size > 0, 'Invalid Tag' AssertionError: Invalid Tag



> V1.3.1 依旧报错
> 
> 直接在Release 下载blrec-1.3.1-win64.zip 后在电脑解压缩 现象： 1.直播间已经开播，运行.bat可以录制，但是录播视频地址会自动改成默认地址（B站录播）与settings.toml文件中设定不符 2.先运行.bat 脚本 >1H，主播开始直播则报错文件如附件，报错时间[2022-01-25 18:56:33,846]，但是文件可以正常录制，同样录播视频地址会自动改成默认地址 [blrec_2022-01-25-112336.log](https://github.com/acgnhiki/blrec/files/7938374/blrec_2022-01-25-112336.log)

个别直播间会出现这种情况，而且是在刚开播的时候。
服务器给的数据有问题，重试几次就正常了。
下次改下异常处理……

**Comment by acgnhiki** [comment]
> V1.3.1 依旧报错
> 
> 直接在Release 下载blrec-1.3.1-win64.zip 后在电脑解压缩 现象： 1.直播间已经开播，运行.bat可以录制，但是录播视频地址会自动改成默认地址（B站录播）与settings.toml文件中设定不符 2.先运行.bat 脚本 >1H，主播开始直播则报错文件如附件，报错时间[2022-01-25 18:56:33,846]，但是文件可以正常录制，同样录播视频地址会自动改成默认地址 [blrec_2022-01-25-112336.log](https://github.com/acgnhiki/blrec/files/7938374/blrec_2022-01-25-112336.log)

把 run.bat 里的 ` -o %outdir%` 删了，下次改下 run.bat 。
