### ISSUE TITLE
添加任务报错

### ISSUE THREAD

**Issue by KakaruHayate** [acgnhiki/blrec#140]
日志如下

`[2022-12-10 12:58:12,884] [ERROR] [httptools_impl] Exception in ASGI application
Traceback (most recent call last):
  File "D:\blrec-v1.12.0-win64\python\Lib\site-packages\uvicorn\protocols\http\httptools_impl.py", line 375, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "D:\blrec-v1.12.0-win64\python\Lib\site-packages\uvicorn\middleware\proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "D:\blrec-v1.12.0-win64\python\Lib\site-packages\fastapi\applications.py", line 208, in __call__
    await super().__call__(scope, receive, send)
  File "D:\blrec-v1.12.0-win64\python\Lib\site-packages\starlette\applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "D:\blrec-v1.12.0-win64\python\Lib\site-packages\starlette\middleware\errors.py", line 181, in __call__
    raise exc
  File "D:\blrec-v1.12.0-win64\python\Lib\site-packages\starlette\middleware\errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "D:\blrec-v1.12.0-win64\python\Lib\site-packages\starlette\middleware\cors.py", line 92, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "D:\blrec-v1.12.0-win64\python\Lib\site-packages\starlette\middleware\cors.py", line 147, in simple_response
    await self.app(scope, receive, send)
  File "D:\blrec-v1.12.0-win64\python\Lib\site-packages\starlette\exceptions.py", line 82, in __call__
    raise exc
  File "D:\blrec-v1.12.0-win64\python\Lib\site-packages\starlette\exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "D:\blrec-v1.12.0-win64\python\Lib\site-packages\starlette\routing.py", line 656, in __call__
    await route.handle(scope, receive, send)
  File "D:\blrec-v1.12.0-win64\python\Lib\site-packages\starlette\routing.py", line 259, in handle
    await self.app(scope, receive, send)
  File "D:\blrec-v1.12.0-win64\python\Lib\site-packages\starlette\routing.py", line 61, in app
    response = await func(request)
  File "D:\blrec-v1.12.0-win64\python\Lib\site-packages\fastapi\routing.py", line 226, in app
    raw_response = await run_endpoint_function(
  File "D:\blrec-v1.12.0-win64\python\Lib\site-packages\fastapi\routing.py", line 159, in run_endpoint_function
    return await dependant.call(**values)
  File "D:\blrec-v1.12.0-win64\python\Lib\site-packages\blrec\web\routers\tasks.py", line 299, in add_task
    real_room_id = await app.add_task(room_id)
  File "D:\blrec-v1.12.0-win64\python\Lib\site-packages\blrec\application.py", line 136, in add_task
    room_id = await ensure_room_id(room_id)
  File "D:\blrec-v1.12.0-win64\python\Lib\site-packages\blrec\bili\helpers.py", line 22, in ensure_room_id
    result = await room_init(room_id)
  File "D:\blrec-v1.12.0-win64\python\Lib\site-packages\blrec\bili\helpers.py", line 16, in room_init
    return await api.room_init(room_id)
  File "D:\blrec-v1.12.0-win64\python\Lib\site-packages\blrec\bili\api.py", line 235, in room_init
    json_res = await self._get_json(self.base_live_api_urls, path, params=params)
  File "D:\blrec-v1.12.0-win64\python\Lib\site-packages\blrec\bili\api.py", line 82, in _get_json
    raise exception
  File "D:\blrec-v1.12.0-win64\python\Lib\site-packages\blrec\bili\api.py", line 75, in _get_json
    return await self._get_json_res(url, *args, **kwds)
  File "D:\blrec-v1.12.0-win64\python\Lib\site-packages\tenacity\_asyncio.py", line 86, in async_wrapped
    return await fn(*args, **kwargs)
  File "D:\blrec-v1.12.0-win64\python\Lib\site-packages\tenacity\_asyncio.py", line 48, in __call__
    do = self.iter(retry_state=retry_state)
  File "D:\blrec-v1.12.0-win64\python\Lib\site-packages\tenacity\__init__.py", line 362, in iter
    raise retry_exc.reraise()
  File "D:\blrec-v1.12.0-win64\python\Lib\site-packages\tenacity\__init__.py", line 195, in reraise
    raise self.last_attempt.result()
  File "concurrent\futures\_base.py", line 439, in result
  File "concurrent\futures\_base.py", line 391, in __get_result
  File "D:\blrec-v1.12.0-win64\python\Lib\site-packages\tenacity\_asyncio.py", line 51, in __call__
    result = await fn(*args, **kwargs)
  File "D:\blrec-v1.12.0-win64\python\Lib\site-packages\blrec\bili\api.py", line 54, in _get_json_res
    async with self._session.get(*args, **kwds) as res:
  File "D:\blrec-v1.12.0-win64\python\Lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\blrec-v1.12.0-win64\python\Lib\site-packages\aiohttp\client.py", line 467, in _request
    with timer:
  File "D:\blrec-v1.12.0-win64\python\Lib\site-packages\aiohttp\helpers.py", line 720, in __exit__
    raise asyncio.TimeoutError from None
asyncio.exceptions.TimeoutError`

**Comment by acgnhiki** [comment]
超时了，可能被风控了？
