### ISSUE TITLE
录制时某些模块报错

### ISSUE THREAD

**Issue by Just-Prog** [acgnhiki/blrec#16]
```
[2022-01-29 21:53:27,857] [CRITICAL] [exception_handler] Unhandled Exception
Traceback (most recent call last):
  File "C:\Users\Prog\AppData\Local\Programs\blrec-1.2.4-win64\python-3.10.1-embed-amd64\Lib\site-packages\blrec\logging\room_id.py", line 41, in wrapper
    return await func(obj, *arg, **kwargs)
  File "C:\Users\Prog\AppData\Local\Programs\blrec-1.2.4-win64\python-3.10.1-embed-amd64\Lib\site-packages\blrec\core\danmaku_dumper.py", line 150, in _dump
    await writer.write_danmu(self._make_danmu(msg))
  File "C:\Users\Prog\AppData\Local\Programs\blrec-1.2.4-win64\python-3.10.1-embed-amd64\Lib\site-packages\blrec\danmaku\io.py", line 116, in write_danmu
    await self._file.write(self._serialize_danmu(danmu))
  File "C:\Users\Prog\AppData\Local\Programs\blrec-1.2.4-win64\python-3.10.1-embed-amd64\Lib\site-packages\blrec\danmaku\io.py", line 159, in _serialize_danmu
    elem = etree.Element('d', attrib=attrib)
  File "src\lxml\etree.pyx", line 3037, in lxml.etree.Element
  File "src\lxml\apihelpers.pxi", line 131, in lxml.etree._makeElement
  File "src\lxml\apihelpers.pxi", line 119, in lxml.etree._makeElement
  File "src\lxml\apihelpers.pxi", line 323, in lxml.etree._initNodeAttributes
  File "src\lxml\apihelpers.pxi", line 334, in lxml.etree._addAttributeToNode
  File "src\lxml\apihelpers.pxi", line 1540, in lxml.etree._utf8
ValueError: All strings must be XML compatible: Unicode or ASCII, no NULL bytes or control characters
```

**Comment by Just-Prog** [comment]
同时弹幕录制也突然结束了

[20220129 嘉然今天吃什么 【B限】燃烧吧 A-SOUL.zip](https://github.com/acgnhiki/blrec/files/7963840/20220129.B.A-SOUL.zip)
