### ISSUE TITLE
ValueError 个别直播间不能录制

### ISSUE THREAD

**Issue by Davinci-D7** [acgnhiki/blrec#162]
不知什么原因，只有单一一个直播间不能录制，cmd里面报红
尝试过删除直播间、重启、刷新数据都不行

直播间：22225994

```
[2023-06-15 13:07:08,164] [WARNING] [analyse] [22225994] Failed to make metadata: AssertionError(('has_video: False, video_analysed: False',))
[2023-06-15 13:07:09,272] [INFO] [stream_fetcher] [22225994] Requesting live stream... https://d1--ov-gotcha05.bilivideo.com/live-bvc/694706/live_32300073_57185103.flv?expires=1686809285&len=0&oi=2012003940&pt=web&qn=10000&trid=10003ef00dfe4de64cffaf2196a2f10d209e&sigparams=cdn,expires,len,oi,pt,qn,trid&cdn=ov-gotcha05&sign=8d38cf1fc1415072781716a3ad5f628d&sk=a306a5ed481f8bef1353a4990a2191b2&p2p_type=0&sl=1&free_type=0&mid=0&source=onetier&trace=0&site=f2761544e563c825f1adab767481b1ea&order=2
[2023-06-15 13:07:09,374] [INFO] [stream_fetcher] [22225994] Response received
[2023-06-15 13:07:09,375] [DEBUG] [defragment] [22225994] Gathering items...
[2023-06-15 13:07:09,375] [DEBUG] [parse] [22225994] Error occurred while parsing stream: ValueError('12 is not a valid CodecID')
Traceback (most recent call last):
  File "D:\Recorder\blrec-v1.13.0-001-win64\python\Lib\site-packages\blrec\flv\operators\parse.py", line 45, in on_next
    tag = reader.read_tag()
          ^^^^^^^^^^^^^^^^^
  File "D:\Recorder\blrec-v1.13.0-001-win64\python\Lib\site-packages\blrec\flv\io.py", line 42, in read_tag
    tag = self._parser.parse_tag(no_body=no_body)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Recorder\blrec-v1.13.0-001-win64\python\Lib\site-packages\blrec\flv\format.py", line 90, in parse_tag
    video_tag_header = self.parse_video_tag_header(header_data)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Recorder\blrec-v1.13.0-001-win64\python\Lib\site-packages\blrec\flv\format.py", line 165, in parse_video_tag_header
    codec_id = CodecID(flag & 0b0000_1111)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "enum.py", line 715, in __call__
  File "enum.py", line 1131, in __new__
ValueError: 12 is not a valid CodecID
[2023-06-15 13:07:09,377] [WARNING] [analyse] [22225994] Failed to make metadata: AssertionError(('has_video: False, video_analysed: False',))
[2023-06-15 13:07:09,377] [ERROR] [exception_handler] [22225994] ValueError('12 is not a valid CodecID')
Traceback (most recent call last):
  File "D:\Recorder\blrec-v1.13.0-001-win64\python\Lib\site-packages\reactivex\observable\catch.py", line 55, in action
    current = next(sources_)
              ^^^^^^^^^^^^^^
StopIteration
[2023-06-15 13:07:09,378] [CRITICAL] [exception_handler] ValueError
Traceback (most recent call last):
  File "D:\Recorder\blrec-v1.13.0-001-win64\python\Lib\site-packages\reactivex\observable\catch.py", line 55, in action
    current = next(sources_)
              ^^^^^^^^^^^^^^
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Recorder\blrec-v1.13.0-001-win64\python\Lib\site-packages\blrec\core\operators\request_exception_handler.py", line 39, in on_error
    raise exc
  File "D:\Recorder\blrec-v1.13.0-001-win64\python\Lib\site-packages\blrec\core\operators\connection_error_handler.py", line 48, in on_error
    raise exc
  File "D:\Recorder\blrec-v1.13.0-001-win64\python\Lib\site-packages\blrec\core\operators\stream_parser.py", line 53, in _before_retry
    raise exc
  File "D:\Recorder\blrec-v1.13.0-001-win64\python\Lib\site-packages\blrec\flv\operators\parse.py", line 45, in on_next
    tag = reader.read_tag()
          ^^^^^^^^^^^^^^^^^
  File "D:\Recorder\blrec-v1.13.0-001-win64\python\Lib\site-packages\blrec\flv\io.py", line 42, in read_tag
    tag = self._parser.parse_tag(no_body=no_body)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Recorder\blrec-v1.13.0-001-win64\python\Lib\site-packages\blrec\flv\format.py", line 90, in parse_tag
    video_tag_header = self.parse_video_tag_header(header_data)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Recorder\blrec-v1.13.0-001-win64\python\Lib\site-packages\blrec\flv\format.py", line 165, in parse_video_tag_header
    codec_id = CodecID(flag & 0b0000_1111)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "enum.py", line 715, in __call__
  File "enum.py", line 1131, in __new__
ValueError: 12 is not a valid CodecID
```

**Comment by Genteure** [comment]
直播流编码是 HEVC 的，只支持 AVC

**Comment by Davinci-D7** [comment]
好吧 谢谢

**Comment by timerring** [comment]
You can refer to this [issue](https://github.com/BililiveRecorder/BililiveRecorder/issues/470).
