### ISSUE TITLE
请问，以前1.05版本运行正常。这次更新1.20之后无法运行

### ISSUE THREAD

**Issue by qqq1942** [acgnhiki/blrec#2]
Active code page: 65001
Traceback (most recent call last):
  File "runpy.py", line 194, in _run_module_as_main
  File "runpy.py", line 87, in _run_code
  File "C:\blrec-1.2.0-win64\python-3.8.9-embed-amd64\Lib\site-packages\blrec\__main__.py", line 3, in <module>
    from .cli.main import main
  File "C:\blrec-1.2.0-win64\python-3.8.9-embed-amd64\Lib\site-packages\blrec\cli\main.py", line 12, in <module>
    from ..setting import DEFAULT_SETTINGS_PATH
  File "C:\blrec-1.2.0-win64\python-3.8.9-embed-amd64\Lib\site-packages\blrec\setting\__init__.py", line 1, in <module>
    from .models import (
  File "C:\blrec-1.2.0-win64\python-3.8.9-embed-amd64\Lib\site-packages\blrec\setting\models.py", line 24, in <module>
    from ..postprocess import DeleteStrategy
  File "C:\blrec-1.2.0-win64\python-3.8.9-embed-amd64\Lib\site-packages\blrec\postprocess\__init__.py", line 1, in <module>
    from .postprocessor import Postprocessor, PostprocessorEventListener
  File "C:\blrec-1.2.0-win64\python-3.8.9-embed-amd64\Lib\site-packages\blrec\postprocess\postprocessor.py", line 17, in <module>
    from ..core import Recorder, RecorderEventListener
  File "C:\blrec-1.2.0-win64\python-3.8.9-embed-amd64\Lib\site-packages\blrec\core\__init__.py", line 1, in <module>
    from .recorder import Recorder, RecorderEventListener
  File "C:\blrec-1.2.0-win64\python-3.8.9-embed-amd64\Lib\site-packages\blrec\core\recorder.py", line 8, in <module>
    from .danmaku_receiver import DanmakuReceiver
  File "C:\blrec-1.2.0-win64\python-3.8.9-embed-amd64\Lib\site-packages\blrec\core\danmaku_receiver.py", line 8, in <module>
    from ..bili.danmaku_client import (
  File "C:\blrec-1.2.0-win64\python-3.8.9-embed-amd64\Lib\site-packages\blrec\bili\danmaku_client.py", line 11, in <module>
    import brotli
  File "C:\blrec-1.2.0-win64\python-3.8.9-embed-amd64\Lib\site-packages\brotli.py", line 8, in <module>
    import _brotli
ImportError: DLL load failed while importing _brotli: 找不到指定的模块。
Press any key to continue . . .

是1.20需求有什么前置运行库？

**Comment by acgnhiki** [comment]
B 站的弹幕协议更新了，新版弹幕协议要使用 [Brotli](https://github.com/google/brotli) 解压。 
安装一下 vc_redist.x64.exe  https://docs.microsoft.com/en-GB/cpp/windows/latest-supported-vc-redist?view=msvc-170
