### ISSUE TITLE
无法添加直播间，KeyError: 'sex'

### ISSUE THREAD

**Issue by 17yjgao** [acgnhiki/blrec#210]
Traceback (most recent call last):
  File "/home/XXX/.local/lib/python3.8/site-packages/blrec/task/task_manager.py", line 50, in load_all_tasks
    await self.add_task(settings)
  File "/home/XXX/.local/lib/python3.8/site-packages/tenacity/_asyncio.py", line 88, in async_wrapped
    return await fn(*args, **kwargs)
  File "/home/XXX/.local/lib/python3.8/site-packages/tenacity/_asyncio.py", line 47, in __call__
    do = self.iter(retry_state=retry_state)
  File "/home/XXX/.local/lib/python3.8/site-packages/tenacity/__init__.py", line 314, in iter
    return fut.result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 437, in result
    return self.__get_result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "/home/XXX/.local/lib/python3.8/site-packages/tenacity/_asyncio.py", line 50, in __call__
    result = await fn(*args, **kwargs)
  File "/home/XXX/.local/lib/python3.8/site-packages/blrec/task/task_manager.py", line 90, in add_task
    await task.setup()
  File "/home/XXX/.local/lib/python3.8/site-packages/blrec/logging/room_id.py", line 42, in wrapper
    return await func(obj, *arg, **kwargs)
  File "/home/XXX/.local/lib/python3.8/site-packages/blrec/task/task.py", line 451, in setup
    await self._live.init()
  File "/home/XXX/.local/lib/python3.8/site-packages/blrec/bili/live.py", line 138, in init
    self._user_info = await self.get_user_info(self._room_info.uid)
  File "/home/XXX/.local/lib/python3.8/site-packages/tenacity/_asyncio.py", line 88, in async_wrapped
    return await fn(*args, **kwargs)
  File "/home/XXX/.local/lib/python3.8/site-packages/tenacity/_asyncio.py", line 47, in __call__
    do = self.iter(retry_state=retry_state)
  File "/home/XXX/.local/lib/python3.8/site-packages/tenacity/__init__.py", line 314, in iter
    return fut.result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 437, in result
    return self.__get_result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "/home/XXX/.local/lib/python3.8/site-packages/tenacity/_asyncio.py", line 50, in __call__
    result = await fn(*args, **kwargs)
  File "/home/XXX/.local/lib/python3.8/site-packages/blrec/bili/live.py", line 231, in get_user_info
    return UserInfo.from_app_api_data(user_info_data)
  File "/home/XXX/.local/lib/python3.8/site-packages/blrec/bili/models.py", line 104, in from_app_api_data
    gender=card['sex'],
KeyError: 'sex'

无法添加直播间，没有sex这个key了

version 1.15.0

**Comment by Davinci-D7** [comment]
version 2.0.0-beta.1 也遇到这个问题
昨晚是可以用的

**Comment by Karmylr** [comment]
> 这个是你被风控了，多重试次就好力 #211

`[ERROR] [task_manager] Failed to add task 24103332 due to: KeyError('sex')`试了很多次都没法添加
