### ISSUE TITLE
最近主站API的风控改了很多，导致BLREC没法添加直播间，附个人解决方案

### ISSUE THREAD

**Issue by KNaiFen** [acgnhiki/blrec#211]
最新：2.0beta2版本，风控情况好很多，同样的电脑1.15启动就是一直报错，2.0beta2直接加上
昨晚重启BLREC的时候发现直播间添加不上，100个直播间开起来后只加有三十多个主播，看日志发现一堆报错，初步怀疑是给风控

我的建议：别请求主站API（api.bilibili.com）拿数据了，像录播姬那样只拿api.live那边的数据？或者增加重试次数，增加间隔

我目前的解决方案：
blrec/task/task_manager.py处
添加for循环，增加重试次数，我个人是改成重试十次，基本能添加上了
还有每次重试最好再加上await asyncio.sleep(3)等待三秒，图里面没有
缺点就是加直播间会慢很多
![3b7f2b3c28686ed6c6ab612fe1cd3173](https://github.com/acgnhiki/blrec/assets/53338804/e3b71d38-2051-4ee7-a059-e614d008cabc)

**Comment by Davinci-D7** [comment]
跟着你的建议改了一下，把settings里的cookie也删除了，还是不能使用

![asdwqwdasd](https://github.com/acgnhiki/blrec/assets/101972575/04444e17-cbf7-42a9-95c4-2ff43442c7ab)

> 2023-12-02 12:13:51.239 | INFO | blrec.application:launch:102 |  - Launching Application...
2023-12-02 12:13:51.240 | DEBUG | blrec.exception.exception_handler:_do_enable:14 |  - Enabled Exception Handler
2023-12-02 12:13:51.240 | DEBUG | blrec.disk_space.space_monitor:_do_enable:55 |  - Enabled space monitor
2023-12-02 12:13:51.240 | DEBUG | blrec.disk_space.space_reclaimer:_do_enable:62 |  - Enabled space reclaimer
2023-12-02 12:13:51.241 | DEBUG | blrec.application:launch:104 |  - Default umask 0
2023-12-02 12:13:51.241 | INFO | blrec.application:launch:105 |  - Launched Application v2.0.0-beta.2
2023-12-02 12:13:51.242 | INFO | blrec.task.task_manager:load_all_tasks:42 |  - Loading all tasks...
2023-12-02 12:13:51.257 | INFO | blrec.task.task_manager:add_task:77 |  - Adding task 2150010...
2023-12-02 12:13:58.779 | ERROR | blrec.task.task_manager:add_task:117 |  - Retry to add task [2150010] Number: 0
2023-12-02 12:14:06.056 | ERROR | blrec.task.task_manager:add_task:117 |  - Retry to add task [2150010] Number: 1
2023-12-02 12:14:13.192 | ERROR | blrec.task.task_manager:add_task:117 |  - Retry to add task [2150010] Number: 2
2023-12-02 12:14:20.677 | ERROR | blrec.task.task_manager:add_task:117 |  - Retry to add task [2150010] Number: 3
2023-12-02 12:14:27.923 | ERROR | blrec.task.task_manager:add_task:117 |  - Retry to add task [2150010] Number: 4
2023-12-02 12:14:34.957 | ERROR | blrec.task.task_manager:add_task:117 |  - Retry to add task [2150010] Number: 5
2023-12-02 12:14:42.077 | ERROR | blrec.task.task_manager:add_task:117 |  - Retry to add task [2150010] Number: 6
2023-12-02 12:14:49.045 | ERROR | blrec.task.task_manager:add_task:117 |  - Retry to add task [2150010] Number: 7
2023-12-02 12:14:55.890 | ERROR | blrec.task.task_manager:add_task:117 |  - Retry to add task [2150010] Number: 8
2023-12-02 12:15:02.970 | ERROR | blrec.task.task_manager:add_task:112 |  - Failed to add task 2150010 due to: KeyError('sex')
2023-12-02 12:15:02.978 | CRITICAL | blrec.exception.exception_handler:_log_exception:24 |  - KeyError('sex')
Traceback (most recent call last):
  File "D:\Recorder\blrec-v2.0.0-beta.2-win64\python\Lib\site-packages\blrec\bili\live.py", line 234, in get_user_info
    user_info_data = await self._webapi.get_user_info(uid)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Recorder\blrec-v2.0.0-beta.2-win64\python\Lib\site-packages\blrec\bili\api.py", line 290, in get_user_info
    json_res = await self._get_json(self.base_api_urls, path, params=params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Recorder\blrec-v2.0.0-beta.2-win64\python\Lib\site-packages\blrec\bili\api.py", line 95, in _get_json
    raise exception
  File "D:\Recorder\blrec-v2.0.0-beta.2-win64\python\Lib\site-packages\blrec\bili\api.py", line 89, in _get_json
    return await self._get_json_res(url, *args, **kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Recorder\blrec-v2.0.0-beta.2-win64\python\Lib\site-packages\tenacity\_asyncio.py", line 88, in async_wrapped
    return await fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Recorder\blrec-v2.0.0-beta.2-win64\python\Lib\site-packages\tenacity\_asyncio.py", line 47, in __call__
    do = self.iter(retry_state=retry_state)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Recorder\blrec-v2.0.0-beta.2-win64\python\Lib\site-packages\tenacity\__init__.py", line 325, in iter
    raise retry_exc.reraise()
          ^^^^^^^^^^^^^^^^^^^
  File "D:\Recorder\blrec-v2.0.0-beta.2-win64\python\Lib\site-packages\tenacity\__init__.py", line 158, in reraise
    raise self.last_attempt.result()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "concurrent\futures\_base.py", line 449, in result
  File "concurrent\futures\_base.py", line 401, in __get_result
  File "D:\Recorder\blrec-v2.0.0-beta.2-win64\python\Lib\site-packages\tenacity\_asyncio.py", line 50, in __call__
    result = await fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Recorder\blrec-v2.0.0-beta.2-win64\python\Lib\site-packages\blrec\bili\api.py", line 67, in _get_json_res
    async with self._session.get(*args, **kwds) as res:
  File "D:\Recorder\blrec-v2.0.0-beta.2-win64\python\Lib\site-packages\aiohttp\client.py", line 1167, in __aenter__
    self._resp = await self._coro
                 ^^^^^^^^^^^^^^^^
  File "D:\Recorder\blrec-v2.0.0-beta.2-win64\python\Lib\site-packages\aiohttp\client.py", line 669, in _request
    resp.raise_for_status()
  File "D:\Recorder\blrec-v2.0.0-beta.2-win64\python\Lib\site-packages\aiohttp\client_reqrep.py", line 1011, in raise_for_status
    raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 404, message='Not Found', url=URL('https://api.live.bilibili.com/x/space/wbi/acc/info?mid=12378594')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Recorder\blrec-v2.0.0-beta.2-win64\python\Lib\site-packages\blrec\task\task_manager.py", line 49, in load_all_tasks
    await self.add_task(settings)
  File "D:\Recorder\blrec-v2.0.0-beta.2-win64\python\Lib\site-packages\tenacity\_asyncio.py", line 88, in async_wrapped
    return await fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Recorder\blrec-v2.0.0-beta.2-win64\python\Lib\site-packages\tenacity\_asyncio.py", line 47, in __call__
    do = self.iter(retry_state=retry_state)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Recorder\blrec-v2.0.0-beta.2-win64\python\Lib\site-packages\tenacity\__init__.py", line 314, in iter
    return fut.result()
           ^^^^^^^^^^^^
  File "concurrent\futures\_base.py", line 449, in result
  File "concurrent\futures\_base.py", line 401, in __get_result
  File "D:\Recorder\blrec-v2.0.0-beta.2-win64\python\Lib\site-packages\tenacity\_asyncio.py", line 50, in __call__
    result = await fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Recorder\blrec-v2.0.0-beta.2-win64\python\Lib\site-packages\blrec\task\task_manager.py", line 90, in add_task
    await task.setup()
  File "D:\Recorder\blrec-v2.0.0-beta.2-win64\python\Lib\site-packages\blrec\task\task.py", line 443, in setup
    await self._live.init()
  File "D:\Recorder\blrec-v2.0.0-beta.2-win64\python\Lib\site-packages\blrec\bili\live.py", line 145, in init
    self._user_info = await self.get_user_info(self._room_info.uid)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Recorder\blrec-v2.0.0-beta.2-win64\python\Lib\site-packages\tenacity\_asyncio.py", line 88, in async_wrapped
    return await fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Recorder\blrec-v2.0.0-beta.2-win64\python\Lib\site-packages\tenacity\_asyncio.py", line 47, in __call__
    do = self.iter(retry_state=retry_state)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Recorder\blrec-v2.0.0-beta.2-win64\python\Lib\site-packages\tenacity\__init__.py", line 314, in iter
    return fut.result()
           ^^^^^^^^^^^^
  File "concurrent\futures\_base.py", line 449, in result
  File "concurrent\futures\_base.py", line 401, in __get_result
  File "D:\Recorder\blrec-v2.0.0-beta.2-win64\python\Lib\site-packages\tenacity\_asyncio.py", line 50, in __call__
    result = await fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Recorder\blrec-v2.0.0-beta.2-win64\python\Lib\site-packages\blrec\bili\live.py", line 238, in get_user_info
    return UserInfo.from_app_api_data(user_info_data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Recorder\blrec-v2.0.0-beta.2-win64\python\Lib\site-packages\blrec\bili\models.py", line 104, in from_app_api_data
    gender=card['sex'],
           ~~~~^^^^^^^
KeyError: 'sex'

**Comment by KNaiFen** [comment]
> 按照你的建议思路，把设置里的cookie也删除了，还是不能使用
> 
> ![asdwqwdasd](https://private-user-images.githubusercontent.com/101972575/287420245-04444e17-cbf7-42a9-95c4-2ff43442c7ab.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE1NzE1OTEsIm5iZiI6MTcwMTU3MTI5MSwicGF0aCI6Ii8xMDE5NzI1NzUvMjg3NDIwMjQ1LTA0NDQ0ZTE3LWNiZjctNDJhOS05NWM0LTJmZjQzNDQyYzdhYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIwM1QwMjQxMzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02YWJmZmM5NTY1YzA3ZTFjNjU3Nzg4ZTAxZWU4OTQwN2ZjNDA1MDAzNjc5ZTk0ZTBjZjJhY2Y3YTM0ZDU3MDg5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.VGQhUMwVSZnHO3ZuP2_0fRnkNWXG2tL7rd77uREFhdE)
> 
> > 2023-12-02 12:13:51.239 | INFO | blrec.application:launch:102 |  - Launching Application...
> > 2023-12-02 12:13:51.240 | DEBUG | blrec.exception.exception_handler:_do_enable:14 |  - Enabled Exception Handler
> > 2023-12-02 12:13:51.240 | DEBUG | blrec.disk_space.space_monitor:_do_enable:55 |  - Enabled space monitor
> > 2023-12-02 12:13:51.240 | DEBUG | blrec.disk_space.space_reclaimer:_do_enable:62 |  - Enabled space reclaimer
> > 2023-12-02 12:13:51.241 | DEBUG | blrec.application:launch:104 |  - Default umask 0
> > 2023-12-02 12:13:51.241 | INFO | blrec.application:launch:105 |  - Launched Application v2.0.0-beta.2
> > 2023-12-02 12:13:51.242 | INFO | blrec.task.task_manager:load_all_tasks:42 |  - Loading all tasks...
> > 2023-12-02 12:13:51.257 | INFO | blrec.task.task_manager:add_task:77 |  - Adding task 2150010...
> > 2023-12-02 12:13:58.779 | ERROR | blrec.task.task_manager:add_task:117 |  - Retry to add task [2150010] Number: 0
> > 2023-12-02 12:14:06.056 | ERROR | blrec.task.task_manager:add_task:117 |  - Retry to add task [2150010] Number: 1
> > 2023-12-02 12:14:13.192 | ERROR | blrec.task.task_manager:add_task:117 |  - Retry to add task [2150010] Number: 2
> > 2023-12-02 12:14:20.677 | ERROR | blrec.task.task_manager:add_task:117 |  - Retry to add task [2150010] Number: 3
> > 2023-12-02 12:14:27.923 | ERROR | blrec.task.task_manager:add_task:117 |  - Retry to add task [2150010] Number: 4
> > 2023-12-02 12:14:34.957 | ERROR | blrec.task.task_manager:add_task:117 |  - Retry to add task [2150010] Number: 5
> > 2023-12-02 12:14:42.077 | ERROR | blrec.task.task_manager:add_task:117 |  - Retry to add task [2150010] Number: 6
> > 2023-12-02 12:14:49.045 | ERROR | blrec.task.task_manager:add_task:117 |  - Retry to add task [2150010] Number: 7
> > 2023-12-02 12:14:55.890 | ERROR | blrec.task.task_manager:add_task:117 |  - Retry to add task [2150010] Number: 8
> > 2023-12-02 12:15:02.970 | ERROR | blrec.task.task_manager:add_task:112 |  - Failed to add task 2150010 due to: KeyError('sex')
> > 2023-12-02 12:15:02.978 | CRITICAL | blrec.exception.exception_handler:_log_exception:24 |  - KeyError('sex')
> > Traceback (most recent call last):
> > File "D:\Recorder\blrec-v2.0.0-beta.2-win64\python\Lib\site-packages\blrec\bili\live.py", line 234, in get_user_info
> > user_info_data = await self._webapi.get_user_info(uid)
> > ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> > File "D:\Recorder\blrec-v2.0.0-beta.2-win64\python\Lib\site-packages\blrec\bili\api.py", line 290, in get_user_info
> > json_res = await self._get_json(self.base_api_urls, path, params=params)
> > ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> > File "D:\Recorder\blrec-v2.0.0-beta.2-win64\python\Lib\site-packages\blrec\bili\api.py", line 95, in _get_json
> > raise exception
> > File "D:\Recorder\blrec-v2.0.0-beta.2-win64\python\Lib\site-packages\blrec\bili\api.py", line 89, in _get_json
> > return await self._get_json_res(url, *args, **kwds)
> > ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> > File "D:\Recorder\blrec-v2.0.0-beta.2-win64\python\Lib\site-packages\tenacity_asyncio.py", line 88, in async_wrapped
> > return await fn(*args, **kwargs)
> > ^^^^^^^^^^^^^^^^^^^^^^^^^
> > File "D:\Recorder\blrec-v2.0.0-beta.2-win64\python\Lib\site-packages\tenacity_asyncio.py", line 47, in **call**
> > do = self.iter(retry_state=retry_state)
> > ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> > File "D:\Recorder\blrec-v2.0.0-beta.2-win64\python\Lib\site-packages\tenacity__init__.py", line 325, in iter
> > raise retry_exc.reraise()
> > ^^^^^^^^^^^^^^^^^^^
> > File "D:\Recorder\blrec-v2.0.0-beta.2-win64\python\Lib\site-packages\tenacity__init__.py", line 158, in reraise
> > raise self.last_attempt.result()
> > ^^^^^^^^^^^^^^^^^^^^^^^^^^
> > File "concurrent\futures_base.py", line 449, in result
> > File "concurrent\futures_base.py", line 401, in __get_result
> > File "D:\Recorder\blrec-v2.0.0-beta.2-win64\python\Lib\site-packages\tenacity_asyncio.py", line 50, in **call**
> > result = await fn(*args, **kwargs)
> > ^^^^^^^^^^^^^^^^^^^^^^^^^
> > File "D:\Recorder\blrec-v2.0.0-beta.2-win64\python\Lib\site-packages\blrec\bili\api.py", line 67, in _get_json_res
> > async with self._session.get(*args, **kwds) as res:
> > File "D:\Recorder\blrec-v2.0.0-beta.2-win64\python\Lib\site-packages\aiohttp\client.py", line 1167, in **aenter**
> > self._resp = await self._coro
> > ^^^^^^^^^^^^^^^^
> > File "D:\Recorder\blrec-v2.0.0-beta.2-win64\python\Lib\site-packages\aiohttp\client.py", line 669, in _request
> > resp.raise_for_status()
> > File "D:\Recorder\blrec-v2.0.0-beta.2-win64\python\Lib\site-packages\aiohttp\client_reqrep.py", line 1011, in raise_for_status
> > raise ClientResponseError(
> > aiohttp.client_exceptions.ClientResponseError: 404, message='Not Found', url=URL('https://api.live.bilibili.com/x/space/wbi/acc/info?mid=12378594')
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last): File "D:\Recorder\blrec-v2.0.0-beta.2-win64\python\Lib\site-packages\blrec\task\task_manager.py", line 49, in load_all_tasks await self.add_task(settings) File "D:\Recorder\blrec-v2.0.0-beta.2-win64\python\Lib\site-packages\tenacity_asyncio.py", line 88, in async_wrapped return await fn(*args, **kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^ File "D:\Recorder\blrec-v2.0.0-beta.2-win64\python\Lib\site-packages\tenacity_asyncio.py", line 47, in **call** do = self.iter(retry_state=retry_state) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "D:\Recorder\blrec-v2.0.0-beta.2-win64\python\Lib\site-packages\tenacity__init__.py", line 314, in iter return fut.result() ^^^^^^^^^^^^ File "concurrent\futures_base.py", line 449, in result File "concurrent\futures_base.py", line 401, in __get_result File "D:\Recorder\blrec-v2.0.0-beta.2-win64\python\Lib\site-packages\tenacity_asyncio.py", line 50, in **call** result = await fn(*args, **kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^ File "D:\Recorder\blrec-v2.0.0-beta.2-win64\python\Lib\site-packages\blrec\task\task_manager.py", line 90, in add_task await task.setup() File "D:\Recorder\blrec-v2.0.0-beta.2-win64\python\Lib\site-packages\blrec\task\task.py", line 443, in setup await self._live.init() File "D:\Recorder\blrec-v2.0.0-beta.2-win64\python\Lib\site-packages\blrec\bili\live.py", line 145, in init self._user_info = await self.get_user_info(self._room_info.uid) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "D:\Recorder\blrec-v2.0.0-beta.2-win64\python\Lib\site-packages\tenacity_asyncio.py", line 88, in async_wrapped return await fn(*args, **kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^ File "D:\Recorder\blrec-v2.0.0-beta.2-win64\python\Lib\site-packages\tenacity_asyncio.py", line 47, in **call** do = self.iter(retry_state=retry_state) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "D:\Recorder\blrec-v2.0.0-beta.2-win64\python\Lib\site-packages\tenacity__init__.py", line 314, in iter return fut.result() ^^^^^^^^^^^^ File "concurrent\futures_base.py", line 449, in result File "concurrent\futures_base.py", line 401, in __get_result File "D:\Recorder\blrec-v2.0.0-beta.2-win64\python\Lib\site-packages\tenacity_asyncio.py", line 50, in **call** result = await fn(*args, **kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^ File "D:\Recorder\blrec-v2.0.0-beta.2-win64\python\Lib\site-packages\blrec\bili\live.py", line 238, in get_user_info 返回 UserInfo.from_app_api_data(user_info_data) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ 文件“D:\Recorder\blrec-v2.0.0-beta.2-win64\python\Lib\site-packages\blrec\bili\models.py”，第 104 行，在 from_app_api_data 中， 性别=card['sex'], ~ ~~~^^^^^^^^ KeyError：'性别'

加个await asyncio.sleep(3)增加间隔，然后就是用别的服务器反代一下主站API来用吧，你这目前的IP估计已经给控的死死的了，没几天解除不掉
