### ISSUE TITLE
添加cookie后一直录制中，但是录制流量和录制总量不变

### ISSUE THREAD

**Issue by SLA225** [acgnhiki/blrec#219]
//这个是日志
2023-12-19 21:28:12.435 | DEBUG | blrec.core.danmaku_dumper:_do_enable:99 | 7016778 - Enabled danmaku dumper
2023-12-19 21:28:12.435 | DEBUG | blrec.core.danmaku_receiver:_do_start:28 | 7016778 - Started danmaku receiver
2023-12-19 21:28:12.436 | DEBUG | blrec.core.cover_downloader:_do_enable:65 | 7016778 - Enabled cover downloader
2023-12-19 21:28:12.438 | DEBUG | blrec.core.stream_recorder:_change_impl:345 | 7016778 - Changed stream recorder impl to HLSStreamRecorderImpl
2023-12-19 21:28:12.438 | DEBUG | blrec.core.stream_recorder_impl:_do_start:287 | 7016778 - Starting stream recorder...
2023-12-19 21:28:12.438 | DEBUG | blrec.hls.metadata_dumper:_do_enable:32 |  - Enabled metadata dumper
2023-12-19 21:28:12.443 | DEBUG | blrec.core.stream_recorder_impl:_do_start:291 | 7016778 - Started stream recorder
2023-12-19 21:28:12.444 | INFO | blrec.core.recorder:_start_recording:473 | 7016778 - Started recording
2023-12-19 21:28:12.446 | INFO | blrec.task.task_manager:add_task:114 |  - Successfully added task 7016778
2023-12-19 21:28:12.448 | INFO | blrec.task.task_manager:load_all_tasks:53 |  - Load all tasks complete
2023-12-19 21:28:12.450 | DEBUG | blrec.bili.live_monitor:_poll_live_status:188 | 7016778 - Started polling live status
2023-12-19 21:28:12.454 | CRITICAL | blrec.exception.exception_handler:_log_exception:24 | 7016778 - PermissionError(13, '连到系统上的设备没有发挥作用。', None, 31, None)
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\lubogongju\python\Lib\site-packages\reactivex\observable\observable.py", line 125, in set_disposable
    subscriber = self._subscribe_core(auto_detach_observer, scheduler)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\Desktop\lubogongju\python\Lib\site-packages\reactivex\observable\observable.py", line 49, in _subscribe_core
    return self._subscribe(observer, scheduler) if self._subscribe else Disposable()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\Desktop\lubogongju\python\Lib\site-packages\blrec\core\operators\progress_bar.py", line 37, in subscribe
    self._pbar = tqdm(
                 ^^^^^
  File "C:\Users\Administrator\Desktop\lubogongju\python\Lib\site-packages\tqdm\std.py", line 1097, in __init__
    self.sp = self.status_printer(self.fp)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\Desktop\lubogongju\python\Lib\site-packages\tqdm\std.py", line 451, in status_printer
    getattr(sys.stderr, 'flush', lambda: None)()
PermissionError: [WinError 31] 连到系统上的设备没有发挥作用。

**Comment by SLA225** [comment]
PS:
一直录的是HLS流

**Comment by KNaiFen** [comment]
我也有这个情况
最近开始大量出现（其实以前也有，少见）拉流的速度一直为0KB，录了几个小时体积也才10M多
我希望能增加一个流量监控或者异常检测什么的，检测到流量长时间为零（例如10min？）或者很低的时候，能自动重新录制，或者尝试别的方法
