### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Karmylr** [acgnhiki/blrec#258]
```
Traceback (most recent call last):
  File "/root/.local/pipx/venvs/blrec/lib/python3.11/site-packages/blrec/bili/danmaku_client.py", line 98, in restart
    await self.stop()
  File "/root/.local/pipx/venvs/blrec/lib/python3.11/site-packages/blrec/utils/mixins.py", line 106, in stop
    await self._do_stop()
  File "/root/.local/pipx/venvs/blrec/lib/python3.11/site-packages/blrec/bili/danmaku_client.py", line 92, in _do_stop
    await self._terminate_message_loop()
  File "/root/.local/pipx/venvs/blrec/lib/python3.11/site-packages/blrec/bili/danmaku_client.py", line 262, in _terminate_message_loop
    await self._message_loop_task
  File "/root/.local/pipx/venvs/blrec/lib/python3.11/site-packages/blrec/logging/room_id.py", line 42, in wrapper
    return await func(obj, *arg, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/pipx/venvs/blrec/lib/python3.11/site-packages/blrec/bili/danmaku_client.py", line 268, in _message_loop
    for msg in await self._receive():
               ^^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/pipx/venvs/blrec/lib/python3.11/site-packages/blrec/bili/danmaku_client.py", line 291, in _receive
    await self._handle_receive_error(exc)
  File "/root/.local/pipx/venvs/blrec/lib/python3.11/site-packages/blrec/bili/danmaku_client.py", line 316, in _handle_receive_error
    await self._retry()
  File "/root/.local/pipx/venvs/blrec/lib/python3.11/site-packages/blrec/bili/danmaku_client.py", line 335, in _retry
    raise aiohttp.WebSocketError(1006, 'Over the maximum of retries')
aiohttp.http_websocket.WebSocketError: Over the maximum of retries
```

**Comment by Karmylr** [comment]
另一种报错信息
```
Traceback (most recent call last):
  File "/home/conter/blrec/src/blrec/event/event_emitter.py", line 40, in _emit
    await coro(*args, **kwds)
  File "/home/conter/blrec/src/blrec/bili/live_monitor.py", line 122, in on_danmaku_received
    danmu_cmd = danmu['cmd']
                ~~~~~^^^^^^^
KeyError: 'cmd'
```
