### ISSUE TITLE
请问在docker里面加入ssl指令启动https之后提示No such file or directory

### ISSUE THREAD

**Issue by qqq1942** [acgnhiki/blrec#28]
详情内容如下

# blrec --key-file path/to/key-file --cert-file path/to/cert-file --api-key bili2233
[Errno 2] No such file or directory
Traceback (most recent call last):
  File "/app/src/blrec/cli/main.py", line 89, in main
    cli()
  File "/usr/local/lib/python3.10/site-packages/typer/main.py", line 214, in __call__
    return get_command(self)(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/typer/main.py", line 500, in wrapper
    return callback(**use_params)  # type: ignore
  File "/app/src/blrec/cli/main.py", line 75, in cli_main
    uvicorn.run(
  File "/usr/local/lib/python3.10/site-packages/uvicorn/main.py", line 447, in run
    server.run()
  File "/usr/local/lib/python3.10/site-packages/uvicorn/server.py", line 68, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/local/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "uvloop/loop.pyx", line 1501, in uvloop.loop.Loop.run_until_complete
  File "/usr/local/lib/python3.10/site-packages/uvicorn/server.py", line 76, in serve
    config.load()
  File "/usr/local/lib/python3.10/site-packages/uvicorn/config.py", line 411, in load
    self.ssl: Optional[ssl.SSLContext] = create_ssl_context(
  File "/usr/local/lib/python3.10/site-packages/uvicorn/config.py", line 127, in create_ssl_context
    ctx.load_cert_chain(certfile, keyfile, get_password)
FileNotFoundError: [Errno 2] No such file or directory

请问是哪里错了了，谢谢大大的无私开发

**Comment by acgnhiki** [comment]
`path/to/key-file` `path/to/cert-file`   `bili2233`  只是示例，要根据你自己的情况修改啊  😂
