### ISSUE TITLE
腾讯云免安装版无法录制

### ISSUE THREAD

**Issue by threewatermeter** [acgnhiki/blrec#29]
Windows Server 2012 R2

错误日志

================================== User Info ==================================
user name        : 3号直播间
gender           : 保密
sign             : 
uid              : 11153765
level            : 2
---------------------------------- Room Info ----------------------------------
title            : 哔哩哔哩音悦台
cover            : 
online           : 9,370
live status      : LIVE
live start time  : 2022-01-18 18:34:26
room id          : 23058
short room id    : 3
area id          : 190
area name        : 唱见电台
parent area id   : 5
parent area name : 电台
tags             : 
description      :
这里是哔哩哔哩官方音乐台喔！一起来听音乐吧ε=ε=(ノ≧∇≦)ノ没想到蒸汽配圣诞下装，意外的很暴露呢=3=
===============================================================================

[2022-03-06 13:05:01,060] [DEBUG] [stream_recorder] [23058] Started stream recorder
[2022-03-06 13:05:01,060] [INFO] [recorder] [23058] Started recording
[2022-03-06 13:05:01,064] [INFO] [application] [23058] Enabled task recorder: 23058
[2022-03-06 13:05:01,077] [CRITICAL] [exception_handler] PermissionError
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\blrec-1.5.0-win64\python-3.10.1-embed-amd64\Lib\site-packages\blrec\core\stream_recorder.py", line 230, in _run
    with tqdm(
  File "C:\Users\Administrator\Desktop\blrec-1.5.0-win64\python-3.10.1-embed-amd64\Lib\site-packages\tqdm\std.py", line 1107, in __init__
    self.sp = self.status_printer(self.fp)
  File "C:\Users\Administrator\Desktop\blrec-1.5.0-win64\python-3.10.1-embed-amd64\Lib\site-packages\tqdm\std.py", line 339, in status_printer
    sys.stderr.flush()
PermissionError: [WinError 31] 连到系统上的设备没有发挥作用。
[2022-03-06 13:05:01,078] [DEBUG] [recorder] Stream recording stopped
[2022-03-06 13:05:01,078] [DEBUG] [stream_recorder] Stopping stream recorder...
[2022-03-06 13:05:04,814] [DEBUG] [recorder] [23058] Stopped recorder
[2022-03-06 13:05:04,814] [DEBUG] [postprocessor] [23058] Stopped postprocessor
[2022-03-06 13:05:04,817] [INFO] [application] [23058] Disabled task recorder: 23058

**Comment by threewatermeter** [comment]
更换2019解决问题

**Comment by acgnhiki** [comment]
可能是 Windows Server 2012 R2 的命令行终端对 UTF-8 的支持有些问题 https://github.com/pypa/pip/issues/5878
