### ISSUE TITLE
这是录制失败吗

### ISSUE THREAD

**Issue by po-lan** [acgnhiki/blrec#36]
![image](https://user-images.githubusercontent.com/42771836/161415797-4c6d7de1-f640-4408-b8e1-b29ced4e6f64.png)
好像是录制失败了，但我去网页里关闭这个主播的录制 再开启就好了
![image](https://user-images.githubusercontent.com/42771836/161415833-d4acad4c-4128-4d0b-8db1-1e4fc6c1fb6a.png)

**Comment by acgnhiki** [comment]
看日志是没接收到推流事件的弹幕没开始录制直播流，一般开播和推流都会发送一个事件弹幕，可能弹幕客户端的连接断了没接收或者和主播的开播方式有关？

**Comment by po-lan** [comment]
具体不太清楚
当时打开网页是录制中 但是没用 体积 和 时长的
之后我关闭 录制 再打开就录上了

**Comment by po-lan** [comment]
下次遇到我再次反馈吧

**Comment by acgnhiki** [comment]
> 具体不太清楚 当时打开网页是录制中 但是没用 体积 和 时长的 之后我关闭 录制 再打开就录上了


1.6.0 （还没发布）已经加了超时自动开始录制了，应该可以避免出现这种情况了。

**Comment by po-lan** [comment]
好的

**Comment by po-lan** [comment]
那我先关闭了

**Comment by po-lan** [comment]
之前的问题又出来了
![image](https://user-images.githubusercontent.com/42771836/162417198-de0df310-5034-45c2-ab91-9f6b4dc3d54b.png)
![image](https://user-images.githubusercontent.com/42771836/162417245-4c6903ca-9931-4d9b-b128-cef5bc0d725d.png)

**Comment by po-lan** [comment]
这是日志
[2022-04-08 18:19:09,601] [DEBUG] [raw_danmaku_dumper] [7362364] Enabled raw danmaku dumper
[2022-04-08 18:19:09,601] [DEBUG] [raw_danmaku_receiver] [7362364] Started raw danmaku receiver
[2022-04-08 18:19:09,602] [DEBUG] [danmaku_dumper] [7362364] Enabled danmaku dumper
[2022-04-08 18:19:09,602] [DEBUG] [danmaku_receiver] [7362364] Started danmaku receiver
[2022-04-08 18:19:09,602] [INFO] [recorder] [7362364] Started recording
[2022-04-08 18:19:09,604] [DEBUG] [live_monitor] [7362364] Number of sequential LIVE status: 1
[2022-04-08 18:23:02,849] [DEBUG] [stream_processor] [62932] 525617 tags have been transfered
[2022-04-08 18:23:02,851] [CRITICAL] [stream_recorder] [62932] OSError(22, '管道的另一端上无任何进程。', None, 233, None)
Traceback (most recent call last):
  File "C:\Users\11140\Desktop\blrec\python-3.10.1-embed-amd64\Lib\site-packages\blrec\core\stream_recorder.py", line 280, in _main_loop
    self._streaming_loop()
  File "C:\Users\11140\Desktop\blrec\python-3.10.1-embed-amd64\Lib\site-packages\blrec\core\stream_recorder.py", line 310, in _streaming_loop
    self._streaming(url)
  File "C:\Users\11140\Desktop\blrec\python-3.10.1-embed-amd64\Lib\site-packages\blrec\core\stream_recorder.py", line 362, in _streaming
    self._stream_processor.process_stream(
  File "C:\Users\11140\Desktop\blrec\python-3.10.1-embed-amd64\Lib\site-packages\blrec\flv\stream_processor.py", line 143, in process_stream
    self._process_stream(stream)
  File "C:\Users\11140\Desktop\blrec\python-3.10.1-embed-amd64\Lib\site-packages\blrec\flv\stream_processor.py", line 211, in _process_stream
    self._process_initial_stream(flv_header, first_data_tag)
  File "C:\Users\11140\Desktop\blrec\python-3.10.1-embed-amd64\Lib\site-packages\blrec\flv\stream_processor.py", line 241, in _process_initial_stream
    self._transfer_tags_until_complete()
  File "C:\Users\11140\Desktop\blrec\python-3.10.1-embed-amd64\Lib\site-packages\blrec\flv\stream_processor.py", line 367, in _transfer_tags_until_complete
    self._transfer_tags(self._read_tags_from_in_stream())
  File "C:\Users\11140\Desktop\blrec\python-3.10.1-embed-amd64\Lib\site-packages\blrec\flv\stream_processor.py", line 391, in _transfer_tags
    self._write_tag(self._correct_ts(tag, self._delta))
  File "C:\Users\11140\Desktop\blrec\python-3.10.1-embed-amd64\Lib\site-packages\blrec\flv\stream_processor.py", line 480, in _write_tag
    self._size_updates.on_next(size)
  File "C:\Users\11140\Desktop\blrec\python-3.10.1-embed-amd64\Lib\site-packages\rx\subject\subject.py", line 55, in on_next
    super().on_next(value)
  File "C:\Users\11140\Desktop\blrec\python-3.10.1-embed-amd64\Lib\site-packages\rx\core\observer\observer.py", line 26, in on_next
    self._on_next_core(value)
  File "C:\Users\11140\Desktop\blrec\python-3.10.1-embed-amd64\Lib\site-packages\rx\subject\subject.py", line 62, in _on_next_core
    observer.on_next(value)
  File "C:\Users\11140\Desktop\blrec\python-3.10.1-embed-amd64\Lib\site-packages\rx\core\observer\autodetachobserver.py", line 26, in on_next
    self._on_next(value)
  File "C:\Users\11140\Desktop\blrec\python-3.10.1-embed-amd64\Lib\site-packages\blrec\core\stream_recorder.py", line 240, in update_size
    progress_bar.update(size)
  File "C:\Users\11140\Desktop\blrec\python-3.10.1-embed-amd64\Lib\site-packages\tqdm\std.py", line 1241, in update
    self.refresh(lock_args=self.lock_args)
  File "C:\Users\11140\Desktop\blrec\python-3.10.1-embed-amd64\Lib\site-packages\tqdm\std.py", line 1346, in refresh
    self.display()
  File "C:\Users\11140\Desktop\blrec\python-3.10.1-embed-amd64\Lib\site-packages\tqdm\std.py", line 1494, in display
    self.sp(self.__str__() if msg is None else msg)
  File "C:\Users\11140\Desktop\blrec\python-3.10.1-embed-amd64\Lib\site-packages\tqdm\std.py", line 350, in print_status
    fp_write('\r' + s + (' ' * max(last_len[0] - len_s, 0)))
  File "C:\Users\11140\Desktop\blrec\python-3.10.1-embed-amd64\Lib\site-packages\tqdm\std.py", line 343, in fp_write
    fp.write(_unicode(s))
  File "C:\Users\11140\Desktop\blrec\python-3.10.1-embed-amd64\Lib\site-packages\tqdm\utils.py", line 145, in inner
    return func(*args, **kwargs)
  File "C:\Users\11140\Desktop\blrec\python-3.10.1-embed-amd64\Lib\site-packages\colorama\ansitowin32.py", line 41, in write
    self.__convertor.write(text)
  File "C:\Users\11140\Desktop\blrec\python-3.10.1-embed-amd64\Lib\site-packages\colorama\ansitowin32.py", line 162, in write
    self.write_and_convert(text)
  File "C:\Users\11140\Desktop\blrec\python-3.10.1-embed-amd64\Lib\site-packages\colorama\ansitowin32.py", line 190, in write_and_convert
    self.write_plain_text(text, cursor, len(text))
  File "C:\Users\11140\Desktop\blrec\python-3.10.1-embed-amd64\Lib\site-packages\colorama\ansitowin32.py", line 195, in write_plain_text
    self.wrapped.write(text[start:end])
  File "C:\Users\11140\Desktop\blrec\python-3.10.1-embed-amd64\Lib\site-packages\colorama\ansitowin32.py", line 41, in write
    self.__convertor.write(text)
  File "C:\Users\11140\Desktop\blrec\python-3.10.1-embed-amd64\Lib\site-packages\colorama\ansitowin32.py", line 162, in write
    self.write_and_convert(text)
  File "C:\Users\11140\Desktop\blrec\python-3.10.1-embed-amd64\Lib\site-packages\colorama\ansitowin32.py", line 190, in write_and_convert
    self.write_plain_text(text, cursor, len(text))
  File "C:\Users\11140\Desktop\blrec\python-3.10.1-embed-amd64\Lib\site-packages\colorama\ansitowin32.py", line 195, in write_plain_text
    self.wrapped.write(text[start:end])
OSError: [WinError 233] 管道的另一端上无任何进程。

**Comment by acgnhiki** [comment]
> 这是日志 [2022-04-08 18:19:09,601] [DEBUG] [raw_danmaku_dumper] [7362364] Enabled raw danmaku dumper [2022-04-08 18:19:09,601] [DEBUG] [raw_danmaku_receiver] [7362364] Started raw danmaku receiver [2022-04-08 18:19:09,602] [DEBUG] [danmaku_dumper] [7362364] Enabled danmaku dumper [2022-04-08 18:19:09,602] [DEBUG] [danmaku_receiver] [7362364] Started danmaku receiver [2022-04-08 18:19:09,602] [INFO] [recorder] [7362364] Started recording [2022-04-08 18:19:09,604] [DEBUG] [live_monitor] [7362364] Number of sequential LIVE status: 1 [2022-04-08 18:23:02,849] [DEBUG] [stream_processor] [62932] 525617 tags have been transfered [2022-04-08 18:23:02,851] [CRITICAL] [stream_recorder] [62932] OSError(22, '管道的另一端上无任何进程。', None, 233, None) Traceback (most recent call last): File "C:\Users\11140\Desktop\blrec\python-3.10.1-embed-amd64\Lib\site-packages\blrec\core\stream_recorder.py", line 280, in _main_loop self._streaming_loop() File "C:\Users\11140\Desktop\blrec\python-3.10.1-embed-amd64\Lib\site-packages\blrec\core\stream_recorder.py", line 310, in _streaming_loop self._streaming(url) File "C:\Users\11140\Desktop\blrec\python-3.10.1-embed-amd64\Lib\site-packages\blrec\core\stream_recorder.py", line 362, in _streaming self._stream_processor.process_stream( File "C:\Users\11140\Desktop\blrec\python-3.10.1-embed-amd64\Lib\site-packages\blrec\flv\stream_processor.py", line 143, in process_stream self._process_stream(stream) File "C:\Users\11140\Desktop\blrec\python-3.10.1-embed-amd64\Lib\site-packages\blrec\flv\stream_processor.py", line 211, in _process_stream self._process_initial_stream(flv_header, first_data_tag) File "C:\Users\11140\Desktop\blrec\python-3.10.1-embed-amd64\Lib\site-packages\blrec\flv\stream_processor.py", line 241, in _process_initial_stream self._transfer_tags_until_complete() File "C:\Users\11140\Desktop\blrec\python-3.10.1-embed-amd64\Lib\site-packages\blrec\flv\stream_processor.py", line 367, in _transfer_tags_until_complete self._transfer_tags(self._read_tags_from_in_stream()) File "C:\Users\11140\Desktop\blrec\python-3.10.1-embed-amd64\Lib\site-packages\blrec\flv\stream_processor.py", line 391, in _transfer_tags self._write_tag(self._correct_ts(tag, self._delta)) File "C:\Users\11140\Desktop\blrec\python-3.10.1-embed-amd64\Lib\site-packages\blrec\flv\stream_processor.py", line 480, in _write_tag self._size_updates.on_next(size) File "C:\Users\11140\Desktop\blrec\python-3.10.1-embed-amd64\Lib\site-packages\rx\subject\subject.py", line 55, in on_next super().on_next(value) File "C:\Users\11140\Desktop\blrec\python-3.10.1-embed-amd64\Lib\site-packages\rx\core\observer\observer.py", line 26, in on_next self._on_next_core(value) File "C:\Users\11140\Desktop\blrec\python-3.10.1-embed-amd64\Lib\site-packages\rx\subject\subject.py", line 62, in _on_next_core observer.on_next(value) File "C:\Users\11140\Desktop\blrec\python-3.10.1-embed-amd64\Lib\site-packages\rx\core\observer\autodetachobserver.py", line 26, in on_next self._on_next(value) File "C:\Users\11140\Desktop\blrec\python-3.10.1-embed-amd64\Lib\site-packages\blrec\core\stream_recorder.py", line 240, in update_size progress_bar.update(size) File "C:\Users\11140\Desktop\blrec\python-3.10.1-embed-amd64\Lib\site-packages\tqdm\std.py", line 1241, in update self.refresh(lock_args=self.lock_args) File "C:\Users\11140\Desktop\blrec\python-3.10.1-embed-amd64\Lib\site-packages\tqdm\std.py", line 1346, in refresh self.display() File "C:\Users\11140\Desktop\blrec\python-3.10.1-embed-amd64\Lib\site-packages\tqdm\std.py", line 1494, in display self.sp(self.**str**() if msg is None else msg) File "C:\Users\11140\Desktop\blrec\python-3.10.1-embed-amd64\Lib\site-packages\tqdm\std.py", line 350, in print_status fp_write('\r' + s + (' ' * max(last_len[0] - len_s, 0))) File "C:\Users\11140\Desktop\blrec\python-3.10.1-embed-amd64\Lib\site-packages\tqdm\std.py", line 343, in fp_write fp.write(_unicode(s)) File "C:\Users\11140\Desktop\blrec\python-3.10.1-embed-amd64\Lib\site-packages\tqdm\utils.py", line 145, in inner return func(*args, **kwargs) File "C:\Users\11140\Desktop\blrec\python-3.10.1-embed-amd64\Lib\site-packages\colorama\ansitowin32.py", line 41, in write self.__convertor.write(text) File "C:\Users\11140\Desktop\blrec\python-3.10.1-embed-amd64\Lib\site-packages\colorama\ansitowin32.py", line 162, in write self.write_and_convert(text) File "C:\Users\11140\Desktop\blrec\python-3.10.1-embed-amd64\Lib\site-packages\colorama\ansitowin32.py", line 190, in write_and_convert self.write_plain_text(text, cursor, len(text)) File "C:\Users\11140\Desktop\blrec\python-3.10.1-embed-amd64\Lib\site-packages\colorama\ansitowin32.py", line 195, in write_plain_text self.wrapped.write(text[start:end]) File "C:\Users\11140\Desktop\blrec\python-3.10.1-embed-amd64\Lib\site-packages\colorama\ansitowin32.py", line 41, in write self.__convertor.write(text) File "C:\Users\11140\Desktop\blrec\python-3.10.1-embed-amd64\Lib\site-packages\colorama\ansitowin32.py", line 162, in write self.write_and_convert(text) File "C:\Users\11140\Desktop\blrec\python-3.10.1-embed-amd64\Lib\site-packages\colorama\ansitowin32.py", line 190, in write_and_convert self.write_plain_text(text, cursor, len(text)) File "C:\Users\11140\Desktop\blrec\python-3.10.1-embed-amd64\Lib\site-packages\colorama\ansitowin32.py", line 195, in write_plain_text self.wrapped.write(text[start:end]) OSError: [WinError 233] 管道的另一端上无任何进程。

colorama 再 cmd  可能有些兼容性问题，可以的话推荐使用 WSL ，相对比较稳定。

**Comment by acgnhiki** [comment]
> ![image](https://user-images.githubusercontent.com/42771836/162462925-2f6d5628-07b0-431b-ae35-97a371dafaf7.png)

这个可能是网络问题导致的，不多见。

**Comment by po-lan** [comment]
好的 ，有时候我 双击 上边
![image](https://user-images.githubusercontent.com/42771836/162580343-bf6e4354-d929-4074-bb72-595a998d35b5.png)
会卡死 退出 但是python 不会推出，程序也不在运行了
估计也是cmd的问题

**Comment by acgnhiki** [comment]
> 好的 ，有时候我 双击 上边 ![image](https://user-images.githubusercontent.com/42771836/162580343-bf6e4354-d929-4074-bb72-595a998d35b5.png) 会卡死 退出 但是python 不会推出，程序也不在运行了 估计也是cmd的问题

Window 的问题，敲下回车就好。

**Comment by po-lan** [comment]
这个 界面会消失的


> > 好的 ，有时候我 双击 上边 ![image](https://user-images.githubusercontent.com/42771836/162580343-bf6e4354-d929-4074-bb72-595a998d35b5.png) 会卡死 退出 但是python 不会推出，程序也不在运行了 估计也是cmd的问题
> 
> Window 的问题，敲下回车就好。

不是 这个界面 会直接消失

**Comment by acgnhiki** [comment]
> 这个 界面会消失的
> 
> > > 好的 ，有时候我 双击 上边 ![image](https://user-images.githubusercontent.com/42771836/162580343-bf6e4354-d929-4074-bb72-595a998d35b5.png) 会卡死 退出 但是python 不会推出，程序也不在运行了 估计也是cmd的问题
> > 
> > 
> > Window 的问题，敲下回车就好。
> 
> 不是 这个界面 会直接消失

那就奇怪了，还是用 WSL 吧。。。

**Comment by po-lan** [comment]
> > 这个 界面会消失的
> > > > 好的 ，有时候我 双击 上边 ![image](https://user-images.githubusercontent.com/42771836/162580343-bf6e4354-d929-4074-bb72-595a998d35b5.png) 会卡死 退出 但是python 不会推出，程序也不在运行了 估计也是cmd的问题
> > > 
> > > 
> > > Window 的问题，敲下回车就好。
> > 
> > 
> > 不是 这个界面 会直接消失
> 
> 那就奇怪了，还是用 WSL 吧。。。

好的 ，我刚会回复

**Comment by po-lan** [comment]
> WSL

我用的是 免安装的 我有时间换成 安装版试试

**Comment by po-lan** [comment]
正在搞wsl 但是 不太清楚 具体怎么搞
![image](https://user-images.githubusercontent.com/42771836/163193414-83c23c45-b2c0-455e-9a05-9fb4c4063708.png)
也可能是我的操作方式有误

**Comment by acgnhiki** [comment]
> 正在搞wsl 但是 不太清楚 具体怎么搞 ![image](https://user-images.githubusercontent.com/42771836/163193414-83c23c45-b2c0-455e-9a05-9fb4c4063708.png) 也可能是我的操作方式有误
 
试下用 pipx 安装，pip 容易出现依赖冲突。

**Comment by po-lan** [comment]
> 

好的
