### ISSUE TITLE
flv 头不正确的直播流录制出错

### ISSUE THREAD

**Issue by acgnhiki** [acgnhiki/blrec#4]
```
Exception in thread StreamRecorder::5293697:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/mnt/e/Projects/blrec/src/blrec/core/stream_recorder.py", line 254, in _run
    self._stream_processor.finalize()
  File "/mnt/e/Projects/blrec/src/blrec/flv/stream_processor.py", line 159, in finalize
    self._complete_file()
  File "/mnt/e/Projects/blrec/src/blrec/flv/stream_processor.py", line 180, in _complete_file
    self._save_extra_metadata()
  File "/mnt/e/Projects/blrec/src/blrec/flv/stream_processor.py", line 555, in _save_extra_metadata
    self._data_analyser.make_metadata(),
  File "/mnt/e/Projects/blrec/src/blrec/flv/data_analyser.py", line 150, in make_metadata
    assert self._has_video and self._video_analysed
AssertionError
```

**Comment by acgnhiki** [comment]
```
assert flv_header.has_video(), 'no video in the stream!'
AssertionError: no video in the stream！
```

**Comment by acgnhiki** [comment]
62c1abf
