### ISSUE TITLE
运行一段时间后报winerror 10022

### ISSUE THREAD

**Issue by saltfish13** [acgnhiki/blrec#49]
![7SB9%O 7XAU58QW`()WQXV2](https://user-images.githubusercontent.com/59356579/164726435-755eed66-acf3-4d9a-9765-2603d51ce8ae.png)

**Comment by acgnhiki** [comment]
这个可能是你网络问题

**Comment by Skimige** [comment]
v1.7.1 成功复现两次
启动参数：`blrec --port xxxx`

**Comment by Skimige** [comment]
```
[2022-07-05 10:15:26,582] [ERROR] [base_events] Exception in callback BaseSelectorEventLoop._accept_connection(<function sta...002995E963D30>, <socket.socke... 25732, 0, 0)>, None, <Server socke...732, 0, 0)>,)>, 2048, None)
handle: <Handle BaseSelectorEventLoop._accept_connection(<function sta...002995E963D30>, <socket.socke... 25732, 0, 0)>, None, <Server socke...732, 0, 0)>,)>, 2048, None)>
Traceback (most recent call last):
  File "E:\Python39\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "E:\Python39\lib\asyncio\selector_events.py", line 164, in _accept_connection
    conn, addr = sock.accept()
  File "E:\Python39\lib\socket.py", line 293, in accept
    fd, addr = self._accept()
OSError: [WinError 10022] 提供了一个无效的参数。
```

基本 100% 复现…… @acgnhiki 能看看吗，只要一开始报这错就打不开 WebUI 了，HTTP 504

**Comment by acgnhiki** [comment]
> ```
> [2022-07-05 10:15:26,582] [ERROR] [base_events] Exception in callback BaseSelectorEventLoop._accept_connection(<function sta...002995E963D30>, <socket.socke... 25732, 0, 0)>, None, <Server socke...732, 0, 0)>,)>, 2048, None)
> handle: <Handle BaseSelectorEventLoop._accept_connection(<function sta...002995E963D30>, <socket.socke... 25732, 0, 0)>, None, <Server socke...732, 0, 0)>,)>, 2048, None)>
> Traceback (most recent call last):
>   File "E:\Python39\lib\asyncio\events.py", line 80, in _run
>     self._context.run(self._callback, *self._args)
>   File "E:\Python39\lib\asyncio\selector_events.py", line 164, in _accept_connection
>     conn, addr = sock.accept()
>   File "E:\Python39\lib\socket.py", line 293, in accept
>     fd, addr = self._accept()
> OSError: [WinError 10022] 提供了一个无效的参数。
> ```
> 
> 基本 100% 复现…… @acgnhiki 能麻烦看看吗，打不开 WebUI HTTP 504 回来一看，就是报了一个这个错 系统是 Windows 10 21H2，Python 3.9，pipx 安装运行

为什么非得给一个无效的参数？

**Comment by Skimige** [comment]
> 为什么非得给一个无效的参数？

🤔 这是 OSError socket 报错，我相信我没给配置文件和启动命令行加任何无效内容，也不可能会反映在 asyncio 模块的 OSError socket 错误上

**Comment by acgnhiki** [comment]
> > 为什么非得给一个无效的参数？
> 
> 🤔 这是 OSError socket 报错，我相信我没给配置文件和启动命令行加任何无效内容，也不可能会反映在 asyncio 模块的 OSError socket 错误上

Python 3.8 和 Python 3.10 也会吗？

**Comment by Skimige** [comment]
> > > 为什么非得给一个无效的参数？
> > 
> > 
> > 🤔 这是 OSError socket 报错，我相信我没给配置文件和启动命令行加任何无效内容，也不可能会反映在 asyncio 模块的 OSError socket 错误上
> 
> Python 3.8 和 Python 3.10 也会吗？

如果怀疑 Python 版本的话，我需要一点时间来测试一下

**Comment by Skimige** [comment]
Py38

```
[2022-07-05 14:30:25,118] [INFO] [task_manager] Load all tasks complete
[2022-07-05 15:24:53,109] [ERROR] [base_events] Exception in callback BaseSelectorEventLoop._accept_connection(<function sta...002A70642BAF0>, <socket.socke... 25733, 0, 0)>, None, <Server socke...5733, 0, 0)>)>, 2048, None)
handle: <Handle BaseSelectorEventLoop._accept_connection(<function sta...002A70642BAF0>, <socket.socke... 25733, 0, 0)>, None, <Server socke...5733, 0, 0)>)>, 2048, None)>
Traceback (most recent call last):
  File "E:\Python38\lib\asyncio\events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "E:\Python38\lib\asyncio\selector_events.py", line 164, in _accept_connection
    conn, addr = sock.accept()
  File "E:\Python38\lib\socket.py", line 292, in accept
    fd, addr = self._accept()
OSError: [WinError 10022] 提供了一个无效的参数。
```

Py39

```
[2022-07-05 14:18:25,908] [INFO] [application] Successfully disabled recorder for task 5169315
[2022-07-05 15:24:48,415] [ERROR] [base_events] Exception in callback BaseSelectorEventLoop._accept_connection(<function sta...001EFF40A7D30>, <socket.socke... 25732, 0, 0)>, None, <Server socke...732, 0, 0)>,)>, 2048, None)
handle: <Handle BaseSelectorEventLoop._accept_connection(<function sta...001EFF40A7D30>, <socket.socke... 25732, 0, 0)>, None, <Server socke...732, 0, 0)>,)>, 2048, None)>
Traceback (most recent call last):
  File "E:\Python39\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "E:\Python39\lib\asyncio\selector_events.py", line 164, in _accept_connection
    conn, addr = sock.accept()
  File "E:\Python39\lib\socket.py", line 293, in accept
    fd, addr = self._accept()
OSError: [WinError 10022] 提供了一个无效的参数。
```


Py310

```
[2022-07-05 14:30:28,053] [INFO] [task_manager] Load all tasks complete
[2022-07-05 15:24:55,794] [ERROR] [base_events] Exception in callback BaseSelectorEventLoop._accept_connection(<function sta...001C3BD487BE0>, <socket.socke... 25734, 0, 0)>, None, <Server socke...5734, 0, 0)>)>, 2048, None)
handle: <Handle BaseSelectorEventLoop._accept_connection(<function sta...001C3BD487BE0>, <socket.socke... 25734, 0, 0)>, None, <Server socke...5734, 0, 0)>)>, 2048, None)>
Traceback (most recent call last):
  File "E:\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "E:\Python310\lib\asyncio\selector_events.py", line 159, in _accept_connection
    conn, addr = sock.accept()
  File "E:\Python310\lib\socket.py", line 293, in accept
    fd, addr = self._accept()
OSError: [WinError 10022] 提供了一个无效的参数。
```

使用 virtualenv，Py38 和 Py310 为 master 分支代码，39 为反馈问题使用的 1.7.4
`blrec --port 2573x -c .\settings.toml`

**Comment by Skimige** [comment]
> 你是怎样用 virtualenv 运行代码的？是否正确安装了依赖？

以 Py310 为例：

```
virtualenv -p E:\Python310\python.exe venv
.\venv\Scripts\Activate.ps1
pip install https://github.com/acgnhiki/blrec/archive/refs/heads/master.zip
blrec --port 25734 -c .\settings.toml
```

**Comment by Skimige** [comment]
观测结果如下：

- 我用 PyCharm 挂上 debugger 打开，它好像就不会出现这个问题
- 然后我更新了一下 Windows（10，21H2，打上七月累积更新补丁），并进行一个重启（P.S. 我这台电脑常年不关机）
- 它 看起来 完全好了

建议后来的朋友们试试更新 Windows 并重启，真实玄学（
