### ISSUE TITLE
171录制问题

### ISSUE THREAD

**Issue by Arukassss** [acgnhiki/blrec#60]
录制的文件好像没发现啥太大问题，但邮件经常有这样的提醒
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\blrec-v1.7.1-win64\python\Lib\site-packages\blrec\flv\stream_processor.py", line 240, in _process_stream
    first_data_tag = self._read_first_data_tag()
  File "C:\Users\Administrator\Desktop\blrec-v1.7.1-win64\python\Lib\site-packages\blrec\flv\stream_processor.py", line 520, in _read_first_data_tag
    for tag in self._read_tags_from_in_stream():
  File "C:\Users\Administrator\Desktop\blrec-v1.7.1-win64\python\Lib\site-packages\blrec\flv\stream_processor.py", line 447, in _read_tags_from_in_stream
    self._parameters_checker.check_tag(tag)
  File "C:\Users\Administrator\Desktop\blrec-v1.7.1-win64\python\Lib\site-packages\blrec\flv\parameters_checker.py", line 53, in check_tag
    raise VideoParametersChanged()
blrec.flv.exceptions.VideoParametersChanged

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\blrec-v1.7.1-win64\python\Lib\site-packages\blrec\core\stream_recorder_impl.py", line 310, in _main_loop
    self._streaming_loop()
  File "C:\Users\Administrator\Desktop\blrec-v1.7.1-win64\python\Lib\site-packages\blrec\core\flv_stream_recorder_impl.py", line 107, in _streaming_loop
    self._streaming(url)
  File "C:\Users\Administrator\Desktop\blrec-v1.7.1-win64\python\Lib\site-packages\blrec\core\flv_stream_recorder_impl.py", line 159, in _streaming
    self._stream_processor.process_stream(
  File "C:\Users\Administrator\Desktop\blrec-v1.7.1-win64\python\Lib\site-packages\blrec\flv\stream_processor.py", line 169, in process_stream
    self._process_stream(stream)
  File "C:\Users\Administrator\Desktop\blrec-v1.7.1-win64\python\Lib\site-packages\blrec\flv\stream_processor.py", line 249, in _process_stream
    self._process_split_stream(flv_header)
  File "C:\Users\Administrator\Desktop\blrec-v1.7.1-win64\python\Lib\site-packages\blrec\flv\stream_processor.py", line 306, in _process_split_stream
    self._complete_file()
  File "C:\Users\Administrator\Desktop\blrec-v1.7.1-win64\python\Lib\site-packages\blrec\flv\stream_processor.py", line 220, in _complete_file
    self._save_extra_metadata()
  File "C:\Users\Administrator\Desktop\blrec-v1.7.1-win64\python\Lib\site-packages\blrec\flv\stream_processor.py", line 671, in _save_extra_metadata
    self._data_analyser.make_metadata(),
  File "C:\Users\Administrator\Desktop\blrec-v1.7.1-win64\python\Lib\site-packages\blrec\flv\data_analyser.py", line 154, in make_metadata
    assert self._has_video and self._video_analysed
AssertionError
问一下是哪里出了问题

**Comment by acgnhiki** [comment]
可以说下是哪个直播间吗？我自己录制看看。
