### ISSUE TITLE
直播间录制错误问题

### ISSUE THREAD

**Issue by qqq1942** [acgnhiki/blrec#65]
异常信息：

Traceback (most recent call last):
  File "/app/src/blrec/core/stream_recorder_impl.py", line 310, in _main_loop
    self._streaming_loop()
  File "/app/src/blrec/core/hls_stream_recorder_impl.py", line 154, in _streaming_loop
    self._playlist_fetcher(url)
  File "/app/src/blrec/core/hls_stream_recorder_impl.py", line 209, in _playlist_fetcher
    self._segment_queue.put(seg, timeout=60)
  File "/usr/local/lib/python3.10/queue.py", line 148, in put
    raise Full
queue.Full

主播直播间链接：https://live.bilibili.com/23343237

**Comment by KNaiFen** [comment]
[blrec_2022-05-15-181746-344225.log](https://github.com/acgnhiki/blrec/files/8752477/blrec_2022-05-15-181746-344225.log)
我也遇到这个BUG了，而且很经常来着，附上一份日志，最末尾部分就是

**Comment by MaiReo** [comment]
看起来是HLS录制问题？

**Comment by acgnhiki** [comment]
HLS 录制的问题，代码已重构，应该不会出现了。  a460c1e9be56e0fe8fc4eca91056587f08aee3e5
