### ISSUE TITLE
1.2.4 Python 3.10 几率性报错 

### ISSUE THREAD

**Issue by chang147** [acgnhiki/blrec#9]
[2022-01-18 19:00:20,544] [DEBUG] [stream_recorder] [XXXXXX] Getting the live stream...
[2022-01-18 19:00:20,731] [DEBUG] [stream_recorder] [XXXXXX] Response received
[2022-01-18 19:00:20,731] [DEBUG] [stream_processor] [XXXXXX] Processing the 4th stream...
[2022-01-18 19:00:20,733] [DEBUG] [stream_processor] [XXXXXX] frame rate: 60.0, video frame interval: 17
[2022-01-18 19:00:20,734] [DEBUG] [stream_processor] [XXXXXX] Reading tags for tag deduplication...
[2022-01-18 19:00:31,822] [DEBUG] [stream_processor] [XXXXXX] Read 2139 tags, total size: 24443100
[2022-01-18 19:00:31,823] [DEBUG] [stream_processor] [XXXXXX] Finding duplicated tags...
[2022-01-18 19:00:31,824] [ERROR] [stream_recorder] [XXXXXX] list index out of range
Traceback (most recent call last):
  File "E:\blrec-1.2.4-win64\python-3.10.1-embed-amd64\Lib\site-packages\blrec\core\stream_recorder.py", line 272, in _main_loop
    self._streaming_loop()
  File "E:\blrec-1.2.4-win64\python-3.10.1-embed-amd64\Lib\site-packages\blrec\core\stream_recorder.py", line 301, in _streaming_loop
    self._streaming(url)
  File "E:\blrec-1.2.4-win64\python-3.10.1-embed-amd64\Lib\site-packages\blrec\core\stream_recorder.py", line 338, in _streaming
    self._stream_processor.process_stream(
  File "E:\blrec-1.2.4-win64\python-3.10.1-embed-amd64\Lib\site-packages\blrec\flv\stream_processor.py", line 142, in process_stream
    self._process_stream(stream)
  File "E:\blrec-1.2.4-win64\python-3.10.1-embed-amd64\Lib\site-packages\blrec\flv\stream_processor.py", line 217, in _process_stream
    self._process_subsequent_stream(first_data_tag)
  File "E:\blrec-1.2.4-win64\python-3.10.1-embed-amd64\Lib\site-packages\blrec\flv\stream_processor.py", line 247, in _process_subsequent_stream
    if (index := self._find_last_duplicated_tag(tags)) >= 0:
  File "E:\blrec-1.2.4-win64\python-3.10.1-embed-amd64\Lib\site-packages\blrec\flv\stream_processor.py", line 412, in _find_last_duplicated_tag
    last_out_tag = self._last_tags[0]
IndexError: list index out of range
[2022-01-18 19:00:31,830] [DEBUG] [retry] [XXXXXX] Retry main_loop after 1.0 seconds

**Comment by acgnhiki** [comment]
e36dedce74430eff5d07faa169d566ef6fcbfe5d
